require("quynh.plugins-setup")
require("quynh.core.options")
require("quynh.core.keymaps")
require("quynh.core.colorscheme")

require("quynh.plugins.comment")
require("quynh.plugins.nvim-tree")
require("quynh.plugins.lualine")
require("quynh.plugins.telescope")
require("quynh.plugins.nvim-cmp")
-- require("quynh.plugins.lsp.mason")
-- require("quynh.plugins.lsp.lspsaga")
-- require("quynh.plugins.lsp.lspconfig")
-- require("quynh.plugins.lsp.null-ls")
require("quynh.plugins.autopairs")
require("quynh.plugins.treesitter")
require("quynh.plugins.gitsigns")
